correcting 'catatlog' plugin spelling error
galasa-dev/maven pull request #100
Opened 2024-02-21 13:32 UTC by Akyiaa

Story: https://github.com/galasa-dev/projectmanagement/issues/1755

2024-02-21 16:41 UTC, galasa-team commented
Build successful

2024-02-22 10:11 UTC, galasa-team commented
Build successful

2024-02-22 10:34 UTC, galasa-team commented
Build successful

2024-02-22 10:51 UTC, KirbyKatcher requested changes

2024-02-22 10:51 UTC, KirbyKatcher commented on galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/DeployTestCatalog.java
> +    protected static boolean setSkip(boolean correctSkip, boolean typoSkip) {
it may be worth while renaming it to `setCorrectBooleanValue`

2024-02-22 10:51 UTC, KirbyKatcher commented on galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/DeployTestCatalog.java
> +    private boolean      skipDeploy = setSkip(correctSkip, typoSkip);
should this not be `skipDeploy = setSkip(correctSkipDeploy,typoSkipDeploy);`

2024-02-22 10:59 UTC, KirbyKatcher approved these changes

2024-02-22 11:00 UTC, galasa-team commented
Build successful

2024-02-22 11:00 UTC, galasa-team commented
Build successful

2024-02-22 11:04 UTC, merged